// WRONG - Extra characters after SUPABASE_ANON_KEY
const supabase = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1aG1pcXZ6aGN1c3h6ZWx4eHBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQxOTA4NTYsImV4cCI6MjA3OTc2Njg1Nn0.JMZ7fL-4A3XJEiZV4kp_TlZwwf_A6V42T_GgZHFs2W8);

// CORRECT
const supabase = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);